### ISSUE TITLE
Spell checker confused by punctuation

### ISSUE THREAD

**Issue by nathany** [SublimeText/AsciiDoc#12]
/cc @wbond Thanks for the help. 

(Sublime Text Dev Build 3100, OS X 10.11.3)

#### It doesn't split on equal signs `=`

The text: `[cols="1,8,1"]`
Sublime thinks this is a word: `cols="1,8,1`

The text: `[start=2]`
Sublime thinks this is a word: `start=2`

The text: `[source,indent=0]`
Sublime thinks this is a word: `indent=0`

#### It doesn't split on opening square bracket `[`

The text: `image::{imagedir}/gopher/mascot.png[,300]`
Sublime thinks this is a word `png[,300`

But oddly this works fine: `image::{imagedir}/playground.png[]`

#### Doesn't split on a closing quote mark `"`

Footnotes are to be placed right up against punctuation (in Asciidoctor)

The text: `such as Python."footnote:[...]`
Sublime thinks this is a word: `Python."footnote`

#### Several issues are sensitive to the scope

The text: `include::{sourcedir}/playground/playground.go[]`
Sublime thinks this is a word: `include::{sourcedir`

But only because it's inside a source block:

```
----
include::{sourcedir}/playground/playground.go[]
----
```

Outside the source block an include or image works fine. `image::{imagedir}/playground.png[]`

Now \`word\` surrounded by back ticks works fine.

But put that in a callout, sidebar, or source block and it still thinks the word is  \`word\` instead of word.

```
====
`word`
====
```

This also is an issue for words starting or ending with a back tick, but only in a callout. Here \'fmt is considered a word, as is Mars.")\`

\`fmt.Print("I am ", 38*365/687, " years old on Mars.")\`

The same is true for a cross reference link, where Sublime thinks that `go>>` is a word in `<<mars.go>>`  when inside a callout, but outside of one it's fine.

The same issue applies to sidebars:

```
****
image::{imagedir}/gopher/ninja.png[,200]
****
```

Unfortunately my AsciiDoc files aren't open source, but I could email them to you if that would help. 

Or you could look though open source .adoc files like:
https://github.com/asciidoctor/asciidoctor.org/tree/master/docs

Thanks.

**Comment by nathany** [comment]
I went through all of these in Build 3107 of Sublime and they are all fixed. Thanks!

**Comment by FichteFoll** [comment]
:+1:
